### ISSUE TITLE
Update 2023 Statewide Parcel Mosaic

### ISSUE THREAD

**Issue by creinier-TxGIO** [TNRIS/gio-data-update#101]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Route Data Shipment [copy data to TNRIS Projects share] @creinier-TxGIO 
- [x] Data Processing [renaming file, data organization]  @creinier-TxGIO 
```
naming convention for shape and fgdb.
stratmap19-landparcels_fipscode_countyname_date.extension
stratmap19-landparcels_48001_anderson_201904.shp
stratmap19-landparcels_48001_anderson_201904.gdb
```
- [x] Quality Assurance @creinier-TxGIO 

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [x] Make collection public  @TNRIS/git-sba 
- [x] Inform TNRIS staff of data availability @creinier-TxGIO 

**QA|QC** 
 **(if collection is made public before 10am you can check after views are refreshed that day)**
 **(if collection is made public after 10am you can check after views are refreshed the next day)**
- [x] Review new collection card after it appears on data.tnris.org @TNRIS/stratmap 
    1. Visually review text wording & formatting
    2. All metadata complete and correct
    3. Collection Footprint drawing properly

**Comment by creinier-TxGIO** [comment]
@csidenblad @mitchellryant - hey ryan and chelsea, joey gave me a quick intro on opening a github issue. i've uploaded the fgdb of statewide parcel dataset to this location: IncomingData\lp\2023_collection\statewide
please let me know if i'm missing anything or you need anything additional. thank you!

**Comment by mitchellryant** [comment]
complete
