### ISSUE TITLE
2023 Address Points Dallas County [Data Update]

### ISSUE THREAD

**Issue by creinier-TxGIO** [TNRIS/gio-data-update#102]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

The shapefile for Dallas County is missing the database file (.dbf) and can't be drawn in arc. Additionally, points from the fgdb feature class weren't successfully translated to the shapefile.

**Data**
- [x] Data Processing [renaming file, data organization] per given naming convention @creinier-TxGIO 
- [x] Quality Assurance @creinier-TxGIO 
	
**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [ ] Update Web Service and API collection link(s) ***(if necessary)*** @TNRIS/git-sba
- [ ] Web Service Link(s) @TNRIS/git-sba

**Comment by creinier-TxGIO** [comment]
@mitchellryant - the address point shapefile and fgdb feature class for Dallas County has been recreated and copied to the following location: IncomingData\ap\2023_collection\updated_counties

**Comment by mitchellryant** [comment]
@creinier-TxGIO are you wanting to push the statewide too?

**Comment by creinier-TxGIO** [comment]
@mitchellryant yes, please! i wasn't sure if i needed to create a new issue for that. thank you

**Comment by mitchellryant** [comment]
complete
