### ISSUE TITLE
Update 2022 Statewide Parcel Mosaic

### ISSUE THREAD

**Issue by creinier-TxGIO** [TNRIS/gio-data-update#103]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Route Data Shipment [copy data to TNRIS Projects share] @creinier-TxGIO 
- [x] Data Processing [renaming file, data organization]  @creinier-TxGIO 
```
naming convention for shape and fgdb.
stratmap19-landparcels_fipscode_countyname_date.extension
stratmap19-landparcels_48001_anderson_201904.shp
stratmap19-landparcels_48001_anderson_201904.gdb
```
- [x] Quality Assurance @creinier-TxGIO 

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba

**QA|QC** 
 **(if collection is made public before 10am you can check after views are refreshed that day)**
 **(if collection is made public after 10am you can check after views are refreshed the next day)**
- [x] Review new collection card after it appears on data.tnris.org @TNRIS/stratmap 
    1. Visually review text wording & formatting
    2. All metadata complete and correct
    3. Collection Footprint drawing properly

**Comment by creinier-TxGIO** [comment]
Hey @csidenblad and @mitchellryant , I've created a new statewide feature class for the 2022 land parcel data. The fgdb has been moved to here: IncomingData\lp\2022_collection\statewide. Please let me know if there is anything that needs to be adjusted. Thank you!

**Comment by mitchellryant** [comment]
@creinier-TxGIO data has been moved to prod share, will be loaded to prod s3 later tonight, also zipped and added to data.tnris.org

**Comment by mitchellryant** [comment]
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/8a7b67c2-b678-4550-8886-439e20e353be)
and
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/38b9b7ee-bd0e-46ca-8e97-ebda9468149c)

**Comment by creinier-TxGIO** [comment]
Looks great! Thanks @mitchellryant
