### ISSUE TITLE
Nueces Bay, Lower Galveston Bay, Houston Ship channels and San Jacinto River Bathymetry

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/gio-data-update#109]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion] @ThorTheDestroyer 
- [x] Quality Assurance @ThorTheDestroyer 

**API\data.tnris.org**
- [x] Create API collection @TNRIS/git-sba
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer 

`If zip file is too large (more than 75MB) please let` @TNRIS/git-sba `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @ThorTheDestroyer 
- [x] Review Description and Formatting @ThorTheDestroyer 
- [x] Add resources  @TNRIS/git-sba 
- [x] Create Single polygon coverage, by merging all polygons together. @ThorTheDestroyer 
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [x] Make collection public  @TNRIS/git-sba
- [ ] Inform GIO staff of data availability @ThorTheDestroyer 

**QA|QC** 
 **(if collection is made public before 10am you can check after views are refreshed that day)**
 **(if collection is made public after 10am you can check after views are refreshed the next day)**
- [x] Review new collection card after it appears on data.tnris.org @TNRIS/stratmap 
    1. Visually review text wording & formatting
    2. All metadata complete and correct
    3. Collection Footprint drawing properly

**Twitter**
- [ ] Draft X content, link, and image in Comment @ThorTheDestroyer 
- [ ] Post X @gwenkruse

**Comment by ThorTheDestroyer** [comment]
@TNRIS/git-sba Do you think we should split these out into separate Collections?

**Comment by mitchellryant** [comment]
@ThorTheDestroyer what do you want to call this? that title is way to long.

are the area adjacent or even semi-adjacent?

**Comment by mitchellryant** [comment]
Maybe 2 or 3 collections

Sheet 1
Sheet 2 & 3
Sheet 4

or

Sheet 1
Sheet 2, 3, & 4

**Comment by mitchellryant** [comment]
@ThorTheDestroyer  **Bathymetry** or **Bathymetric Lidar**?

Nueces Bay Bathymetry - 53518e5c-f15b-4471-ad7d-b4fce2eef220
San Jacinto River and Ship Channel Shallows Bathymetry - fac7bf4c-5084-4166-a75f-d268d3b7d0af
Lower Galveston Bay Bathymetry - 31a76e61-4af3-4f80-af8a-64ed4d63d395

**Comment by mitchellryant** [comment]
I'll check on the progress on Monday.

**Comment by ThorTheDestroyer** [comment]
Collection dems have a resolution, but the closest thing to resolution would be the track spacing which is not consistent or is unknown for the multibeam. I haven't seen any language regarding the point spacing or resolution of the soundings.

**Comment by mitchellryant** [comment]
SBA work is done, have a great day!
