### ISSUE TITLE
TXDOT Collections 369082 & 368716

### ISSUE THREAD

**Issue by A-M-Pearce** [TNRIS/gio-data-update#111]
Hey @mitchellryant,

Please delete all frames within LORE-Collection\TXDOT-1988-369082\frames, and then move all frames from LORE-Collection\TXDOT-1988-368716\frames into LORE-Collection\TXDOT-1988-369082\frames. Indexes within each respective collection are correct and do not need to be updated. 

Thank you!

**Comment by mitchellryant** [comment]
complete!
