### ISSUE TITLE
Texas NHAP 1981

### ISSUE THREAD

**Issue by A-M-Pearce** [TNRIS/gio-data-update#90]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @A-M-Pearce 
- [x] Download Data to IncomingData  @A-M-Pearce 
- [x] Data Processing [renaming file, data organization, data conversion]  @A-M-Pearce 
- [x] Creation of derivative products [compressed images] @A-M-Pearce 
- [x] QC Imagery  @A-M-Pearce 

**API\data.tnris.org**
- [x]  Create API collection @TNRIS/git-sba 
- [x] Create LORE Collection Record within API LORE  @A-M-Pearce 
- [x] Set Collection Record to **Not** Public within API LORE  @A-M-Pearce 
- [x] Complete LCD API console collection form including metadata and description @A-M-Pearce
- [x] Upload supplemental info (breaklines, reports, index) @A-M-Pearce

`If zip file is too large (more than 75MB) please let` @TNRIS/git-sba `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @A-M-Pearce
- [x] Review Description and Formatting @A-M-Pearce
- [x] Add resources @TNRIS/git-sba
- [x] Create Single polygon coverage, by merging all polygons together. @A-M-Pearce
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move Data to S3 TNRIS Data Warehouse LCD  @TNRIS/git-sba 
- [x] Copy data to production shares @TNRIS/git-sba
- [x] Delete Dataset within IncomingData  @A-M-Pearce 
- [x] Make collection public @TNRIS/git-sba
- [x] Web Service Link(s) @TNRIS/git-sba 
- [ ] Inform GIO staff of data availability @A-M-Pearce

**QA|QC** 
 **(if collection is made public before 10am you can check after views are refreshed that day)**
 **(if collection is made public after 10am you can check after views are refreshed the next day)**
- [x] Review new collection card after it appears on data.tnris.org @TNRIS/stratmap 
	1. Visually review text wording & formatting
	2. All metadata complete and correct
	3. Collection Footprint drawing properly

**Twitter**
- [ ] Draft X content, link, and image in Comment @@A-M-Pearce
- [ ] Post X @TNRIS/dim

**Comment by mitchellryant** [comment]
Each Tiff zip will be about 1GB. not much compression on image files, just an FYI.

**Comment by mitchellryant** [comment]
all @TNRIS/git-sba work is complete (excpet making public).

**Comment by A-M-Pearce** [comment]
@mitchellryant all Data and API\data.tnris.org tasks have been completed

**Comment by mitchellryant** [comment]
@A-M-Pearce you want to link out to the USDA NHAP_All Web Service, even though we have one in the collection?




I added back the link to the Exp Builder App.
 
just an **FYI** going forward we will need to href  links. 
example:
`<a href="https://portal.tnris.org/portal/apps/experiencebuilder/experience/?id=496a71d4ad5648699ba9eb94e7421194" target="_blank">USGS 1981-1983 NHAP Interactive Map</a>`

**Comment by A-M-Pearce** [comment]
No, you are right. We don't need to include the USDA NHAP_All Web Service. Thanks @mitchellryant!

**Comment by mitchellryant** [comment]
@A-M-Pearce @ThorTheDestroyer Since the collection was made public after 10am, you will be to check the collection card in the morning. you can adjust text and other metadata then. if some thing is wrong with the downloads please have CR look at the lambdas.

**Comment by mitchellryant** [comment]
just closing due to lack of movement!
