### ISSUE TITLE
Texas NAIP 2022

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/gio-data-update#94]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @LaurenKirk
- [x] Route Data Shipment (copy data to TNRIS Projects share) @LaurenKirk 
- [x] Data Processing (renaming file, data organization) @LaurenKirk 
- [x] Creation of derivative products [compressed images] @LaurenKirk
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @TNRIS/git-sba
- [x] Complete API console collection form including metadata and description @LaurenKirk
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @TNRIS/git-sba `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @LaurenKirk
- [x] Review Description and Formatting @LaurenKirk https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @TNRIS/git-sba
- [x] Create Single polygon coverage, by merging all polygons together. @LaurenKirk
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @TNRIS/git-sba
- [x] Make collection public @TNRIS/git-sba
~- [ ] Web Service Link(s) @TNRIS/git-sba~
- [x] Inform GIO staff of data availability @LaurenKirk

**QA|QC** 
 **(if collection is made public before 10am you can check after views are refreshed that day)**
 **(if collection is made public after 10am you can check after views are refreshed the next day)**
- [x] Review new collection card after it appears on data.tnris.org @TNRIS/stratmap 
	1. Visually review text wording & formatting
	2. All metadata complete and correct
	3. Collection Footprint drawing properly

**Twitter**
- [x] Draft X content, link, and image in Comment @LaurenKirk 
- [ ] Post X @TNRIS/dim

**Comment by csidenblad** [comment]
API collection has been created. https://api.tnris.org/admin/lcd/collection/49450905-d993-438f-8d8b-50129030744d/change/?_changelist_filters=q%3Dnaip

**Comment by LaurenKirk** [comment]
@csidenblad API collection has been filled out.  Currently have NC/CIR CCMs.  Awaiting DOQQ arrival.  All CCM's have been renamed, moved, QAQC'ed and are on Gorgoroth. Please publish CCMs when convenient.  I will return and finish full tasks upon DOQQ arrival.

**Comment by csidenblad** [comment]
@LaurenKirk It looks like the naming convention does not match previous years. the file names are missing county names. Please see 2020 for example and rename correctly.
**naip20-cir-60cm-anderson_48001**

**Comment by LaurenKirk** [comment]
@csidenblad LOL whoops

**Comment by LaurenKirk** [comment]
@csidenblad everything has been renamed and collection footprint created/uploaded.  Let me know if you need anything else.  I'll "notify staff" and draft tweet.

**Comment by mitchellryant** [comment]
@LaurenKirk  Please href the links in the desc.

just an **FYI** going forward we will need to href  links. 
example:
`<a href="https://portal.tnris.org/portal/apps/experiencebuilder/experience/?id=496a71d4ad5648699ba9eb94e7421194" target="_blank">USGS 1981-1983 NHAP Interactive Map</a>`

**Comment by mitchellryant** [comment]
@LaurenKirk can they be the source and a parnter?

![image](https://github.com/TNRIS/gio-data-update/assets/8459928/f5492402-5026-4f48-8c3b-4155ec4f4f64)

**Comment by LaurenKirk** [comment]
> @LaurenKirk Please href the links in the desc.
> 
> just an **FYI** going forward we will need to href links. example: `<a href="https://portal.tnris.org/portal/apps/experiencebuilder/experience/?id=496a71d4ad5648699ba9eb94e7421194" target="_blank">USGS 1981-1983 NHAP Interactive Map</a>`

Done!

**Comment by LaurenKirk** [comment]
> @LaurenKirk can they be the source and a parnter?
> 
> ![image](https://user-images.githubusercontent.com/8459928/276364590-f5492402-5026-4f48-8c3b-4155ec4f4f64.png)

Fixed!

**Comment by mitchellryant** [comment]
Create Single polygon coverage, by merging all polygons together. @LaurenKirk

- [ ] If your area is county based please use the TxDOT Generalized Boundaries.
- Use Editing Merge, not Merge Tool.
- No Vertices, holes, or donuts (unless to directly shows in the data)
- Projected shape to 4326
- Generalized shape by 10m
- Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
- **Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/**


![image](https://github.com/TNRIS/gio-data-update/assets/8459928/4e7ab10f-0711-4879-ac0c-801d6713c622)

**Comment by LaurenKirk** [comment]
> Create Single polygon coverage, by merging all polygons together. @LaurenKirk
> 
> * [x]  If your area is county based please use the TxDOT Generalized Boundaries.
> * Use Editing Merge, not Merge Tool.
> * No Vertices, holes, or donuts (unless to directly shows in the data)
> * Projected shape to 4326
> * Generalized shape by 10m
> * Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
> * **Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/**
> 
> ![image](https://user-images.githubusercontent.com/8459928/276366199-4e7ab10f-0711-4879-ac0c-801d6713c622.png)

@mitchellryant done!

**Comment by mitchellryant** [comment]
@LaurenKirk thought it was more than Cameron?
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/3355e9fa-6cb2-493e-be0b-b388f1a81e3f)

**Comment by LaurenKirk** [comment]
> @LaurenKirk thought it was more than Cameron? ![image](https://user-images.githubusercontent.com/8459928/276371030-3355e9fa-6cb2-493e-be0b-b388f1a81e3f.png)

@mitchellryant fixed/done!

**Comment by mitchellryant** [comment]
@TNRIS/stratmap Since the collection was made public after 10am, you will be to check the collection card in the morning. you can adjust text and other metadata then. if some thing is wrong with the downloads please have CR look at the lambdas.

**Comment by mitchellryant** [comment]
just closing due to lack of movement!

**Comment by LaurenKirk** [comment]
@mitchellryant final QAQC is complete of the JP2 tiles.  They are ready to be moved and are in Incoming Data.  Let me know if you need anything else!

**Comment by mitchellryant** [comment]
@LaurenKirk where are the jp2?
there are 17,277 tiffs. are there that many JP2, J2W, and Meta Xml?

**Comment by LaurenKirk** [comment]
@mitchellryant jp2s are here: IncomingData\imagery\naip-2022-nc-cir-60cm\jp2tiles
Yes, there are the same number of jp2 and j2w files as there are tiffs

**Comment by mitchellryant** [comment]
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/1ef0a08e-c02f-4139-8813-e216f04bb72e)
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/8a58736d-e7e6-4a34-90f1-dec97be72e05)

**Comment by mitchellryant** [comment]
@LaurenKirk metadata xmls have been copied to jp2

**Comment by LaurenKirk** [comment]
@mitchellryant I've validated the same number of jp2, j2w and xml files. Should be good to go.

**Comment by mitchellryant** [comment]
@LaurenKirk Some JP2 are not right.

2897411-2987414
2897421-2987424
2897431-2987434

**JP2**
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/203ffd91-8aff-4aa6-91d8-b25ac651999a)

**TIFF**
![image](https://github.com/TNRIS/gio-data-update/assets/8459928/bfc18e60-c932-4c3a-8244-3d51643e7b85)

**Comment by LaurenKirk** [comment]
@mitchellryant reprocessed those 12 tiles.  They all draw correctly as JP2s in ArcPro.  You can find them and their ancillary files here: IncomingData\imagery\naip-2022-nc-cir-60cm\jp2tiles
